nome = str(input('Digite seu nome completo: ')).strip()
print('Analisando seu nome...')
print('-----'*10)
print(f'Seu nome em maiusculo é: {nome.upper()}')
print('-----'*10)
print(f'Seu nome em minusculo é: {nome.lower()}')
print('-----'*10)
print(f'Seu nome completo tem {len(nome)-nome.count(' ')} letras')
print('-----'*10)
print(f'Seu primeiro nome tem {nome.find(' ')} Letras')
print('-----'*10)
separa = nome.split()
print(f'Seu primeiro nome e {separa[0]} e seu sobrenome {separa[1]}')
print('-'*10)
